// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sinksjsnbdgtcpocvjwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpbmtzanNuYmRndGNwb2N2andqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3NzI4NDksImV4cCI6MjA4ODM0ODg0OX0.hitmc5o3ErA5pYAj7jFPKkQPH0iubQCAQnyHzCfdRxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});